name: foresight_plus
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  syncfusion_flutter_gauges: ^29.1.38
  file_picker: ^10.1.2
  permission_handler: ^11.0.1
  device_info_plus: ^11.3.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "lib/assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
